logging:
  level:
    root: INFO
    com.cgms: DEBUG
spring:
  quartz:
    job-store-type: memory

aws:
  region: your-aws-region
  access-key: your-access-key
  secret-key: your-secret-key
  s3:
    bucket-name: your-bucket-name